### ISSUE TITLE
Make .exe file

### ISSUE THREAD

**Issue by catursawah** [birchwork/ore-ace#2]
can u explaind how to make / compaile ore.exe

**Comment by birchwork** [comment]
First you need a rust environment, then follow below:

1. run `cargo build --release`
2. visit the `target/release` folder and you will see the `ore.exe` file
3. in the same folder as ore.exe, open cmd
4. type `.\ore --rpc <your rpc url> --keypair <your bs58 private key>  mine`
5. `--rpc` and `--keypair ` are required parameter
6. `--jito-enable`, `--jito-fee`, `--jito-client`, `--config-file`, `--priority-fee` are optional and have their own default values
7. if you want to use jito just set `--jito-enable` and `--jito-fee`, `--priority-fee` not recommended for use
8. `beneficiary` not available, don't use it
use jito example: `.\ore --jito-enable --rpc https://api.mainnet-beta.solana.com --keypair <bs58 private key> mine`

**Comment by birchwork** [comment]
btw, recommended to use `--thread`, behind mine, and the value is 4

**Comment by ChengmingFan** [comment]
> btw, recommended to use `--thread`, behind mine, and the value is 4

`--threads` 😊

**Comment by catursawah** [comment]
![image](https://github.com/birchwork/ore-ace/assets/83405015/8cab3094-2a5e-45ef-ae6a-a722ea5b89d8)
theres no ore.exe just file ore for linux

**Comment by birchwork** [comment]
my suggestion: build on windows, if u want to build it on Linux system, follow the below:
`rustup target add x86_64-pc-windows-gnu`
`rustup toolchain install stable-x86_64-pc-windows-gnu`
`cargo build --target x86_64-pc-windows-gnu`
