### ISSUE TITLE
how to use jito?

### ISSUE THREAD

**Issue by ChengmingFan** [birchwork/ore-ace#3]
Thanks for your project!
sorry for inconvenience! I want ask how to use jito?  Shall I apply in jito official website with my public key firstly? And the what the mean of jito rpc? how to get it?

**Comment by birchwork** [comment]
about jito, u can visit the following [Jito docs](https://jito-labs.gitbook.io/mev/searcher-resources/getting-started). In the src/main.rs file, the default value for jito_client is already set, so you can use this default rpc.  in practice, the performance using Jito might not meet expectations. u might want to try running the program from the [priority branch](https://github.com/birchwork/ore-ace/tree/priority)

**Comment by birchwork** [comment]
btw, QuickNode does not support `getPriorityFeeEstimate`, suggest using [helius](https://www.helius.dev/)
